In [11]:
#1. Import the numpy package under the name np (★☆☆)
import numpy as np

In [10]:
#2. Print the numpy version and the configuration (★☆☆)
np.version.version

'1.22.4'

In [12]:
#3. Create a null vector of size 10 (★☆☆)
x=np.zeros(10)

In [14]:
#6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [13]:
#7. Create a vector with values ranging from 10 to 49 (★☆☆)
Z=np.arange(10,50)
print (Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [15]:
#8. Reverse a vector (first element becomes last) (★☆☆)
a = np.arange(10,50)
a= a[::-1]
print (a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [16]:
#9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
Z = np.arange(9).reshape(3,3)
print (Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int32),)


In [18]:
#11. Create a 3x3 identity matrix (★☆☆)
Z= np.eye(3)
print (Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
#12. Create a 3x3x3 array with random values (★☆☆)
Z = np.random.uniform((3,3,3))
print (Z)

[2.03010832 2.95782633 2.75272778]


In [20]:
#13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.016398234467591477 0.9994024829445178


In [21]:
#14. Create a random vector of size 30 and find the mean value (★☆☆)
Z = np.random.random(10)
m = Z.mean()
print (m)

0.6635202850832789


In [27]:
#15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
Z = np.ones((10,10))
Z[1:-1,1:-1]=0

In [28]:
#17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

nan
False
False
nan
False

False

In [29]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [30]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [18]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

data = np.arange(11)
data[(data>3) & (data < 8)] *= -1

In [33]:
#28. What are the result of the following expressions? (★☆☆)
#np.array(0) / np.array(0)
#np.array(0) // np.array(0)
#np.array([np.nan]).astype(int).astype(float)
print(np.array(0)// np.array(0))
print(np.array(0)//np.array(0.))
print(np.array(0)//np.array(0))
print(np.array(0)//np.array(0.))

#0
#nan
#0
#nan

0
nan
0
nan


In [34]:
#30. How to find common values between two arrays? (★☆☆)
ar1 = np.array([0, 1, 2, 3, 4])
ar2 = [1, 3, 4]
  
print(np.intersect1d(ar1, ar2))

[1 3 4]


In [21]:
#40. Create a random vector of size 10 and sort it (★★☆)
Z = np.random.random(10)
Z.sort()
Z

In [31]:
#42. Consider two random array A and B, check if they are equal (★★☆)
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [32]:
#44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.70448298 0.78667712 0.97345164 0.3691029  0.9003007  0.30326865
 0.45685859 0.88083997 0.74425781 0.59740143]
[0.94159083 0.75752391 0.53415963 1.01752199 0.82425963 1.32322829
 0.85052974 0.60988869 0.45792952 1.0635225 ]


In [24]:
#53. How to convert a float (32 bits) array into an integer (32 bits) in place?
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)

In [25]:
#58. Subtract the mean of each row of a matrix (★★☆)
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)
Y